#!/bin/bash

echo "🚨 NAS 7008 포트 긴급 수정"
echo "📌 수동으로 실행 필요한 명령어들:"
echo ""
echo "1. NAS SSH 접속:"
echo "   ssh joopok@192.168.0.109"
echo ""
echo "2. 다음 명령어 실행:"
echo "   cd /volume1/docker/jenkins/jenkins_home/workspace/dabang-movers-app2"
echo "   sudo /usr/local/bin/docker run -d --name app-7008 -v \$(pwd):/app -w /app -p 7008:7008 -e PORT=7008 --restart unless-stopped node:20-alpine sh -c 'npm install && npm run build && npm run start'"
echo ""
echo "3. 또는 Container Manager에서:"
echo "   - http://192.168.0.109:5000 접속"
echo "   - Container Manager 열기"
echo "   - 새 컨테이너 생성"
echo "   - 포트: 7008"
echo "   - 이미지: node:20-alpine"
echo ""
echo "sudo 비밀번호 입력이 필요합니다!"